<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcooiwb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcooiwb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBcooiwb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBcooiwb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBcooiwb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bcooiwb',
    'container.build_id' => 'b260c54a',
    'container.build_time' => 1534055958,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcooiwb');
